### PR TITLE
[html] Do  not use zero-width-joiner to implement non-breakable space.

### PR DESCRIPTION
**Pull request by maranget**
Some browsers (_e.g._ Firefox) render zwj poorly. Hence this alternative
implementation of space that should not break as sequence of non-breaking
spaces (U+2040) and narrow no-break spaces (U+202F).

This PR intends to solve issue #60.

### CODE REVIEW

**Comment by maranget** [comment]
@cspiel Hi, would you please comment on this PR? See also issue #60.

**Comment by cspiel** [comment]
THX, @maranget for the fix!  I have run my all my old tests and your
change looks perfect to me.  The line-breaking behavior and the persistence
of non-breakable spaces remains exactly the same even at the beginning
of paragraphs.

Needless to say that I _very much_ prefer fixing Hevea instead of every
project that uses it as conversion engine.

**Comment by maranget** [comment]
@cspiel Thanks a lot for your comment.  I'll merge this PR. Fixing the ocaml manual post-processing is another story.

**Comment by sanette** [comment]
@maranget I assume that in your original post you wanted to say U+2004 instead of U+2040 ?
If I understand correctly, the sequence 2004 200D that appeared for instance in
'Chapter\u2004\u200d2\u2003The module system'
will now be replaced by 2004 202F
Could you confirm? thx!

**Pull request merged**
