### PR TITLE
Set `html` element's attribute `lang` according to document's language

### PR DESCRIPTION
**Pull request by cspiel**
This P/R addresses issue #25.  Its primary
target is to provide transparent setting of the
`lang` attribute for the whole HTML document
based on the LaTeX
  * document options,
  * language packages, or
  * babel's
    * package options or
    * `\selectlanguage` (in the preamble)

It has turned out that the central function, a
map from babel language names
(e.g. `swissgerman`) to language codes
(e.g. `de-CH`) is also suitable to implement
some of the missing babel environments and
macros e.g. `\foreignlanguage{LANG}{TEXT}`.
Their implementation is trivial.  The
documentation has been extended and updated
accordingly.

**Known Problem:** Babel allows for a quirky way
to set the document's main language

```latex
\usepackage[main=italian,french]{babel}
```

which makes `italian` the main language.  This
P/R partially implements parsing the `main`
modifier, but ''babel.hva'' ignores it (due to
standard parsing of the package's options) and
thus the document's main language is wrongly
detected when `main=` is used.

### CODE REVIEW

**Comment by maranget** [comment]
Hi, I am a bit concerned about default behaviour. At the moment if no language is specified, the PR emits a `lang="en"` attribute to the `<html .. >` element. Wouln't the previous behaviour of not emitting any `lang` attribute be more logical ?

I'd also like to have a look at the `main=...` question, as I do not understand exactly why babel.hva cannot parse the main=italian optional package argument.

**Comment by maranget** [comment]
> I'd also like to have a look at the `main=...` question, as I do not understand exactly why babel.hva cannot parse the main=italian optional package argument.
My commit to your PR attempt precisely to do this. I had to modify `package.hva` a bit. Would you please have a look on it ?

**Comment by maranget** [comment]
> Code looks good and passed all my tests.
> Now `main=` works as expected.

I am glad it does. What about my other comment on *not* having a lang attribute when no language is specified?

**Comment by cspiel** [comment]
I know you are afraid of breaking backward compatibility with
the introduction of `lang="en"` as default.

1. A document that does not mention any language, e.g. via babel
  is treated as (US-)English by LaTeX/TeX -- in particular when it comes
  to hyphenation.  So, it is transparent to the user that her Hevea-translated
  HTML-version of the document gets `lang="en"`.  The document's language
  should be a document property and not a (configurable?!) browser
  property.
1. [W3](https://www.w3.org/International/questions/qa-html-language-declarations) kind of cheers for this attribute, but it really plays out with
  translation/interoperability and there with screen readers.

So, I'm inclined to have a default `lang`-attribute, though I'm not sure which
to prefer: `en` or `en-US`.

**Comment by maranget** [comment]
Hi,

Ok I see this, although I'd rather had have language unspecified for pages in English, that pages in French with lang="en" specification, I'll follow your suggestion and merge the PR.

Thanks a lot for your contribution.

**Pull request merged**
